--- name:default

# From Frame for the transformer
localization_source_frame: 'body'

#Maximum number of sensor camera poses in the filter state.
maximum_number_sensor_poses: 20

# Desired update period. It cannot be smaller that the visual features samples period.
update_period: 0.4

# Filter update type
update_type: :EKF_OB #:EKF_OB #:UKF #NO_UPDATE

# the global name that should be used for the internal navigation frame
navigation_frame: navigation
# the global name that should be used for the internal world frame
# It is also used by the localization to get the reference frame in which
# the body position can be used.
world_frame: navigation #world

body_frame: body
sensor_frame: left_camera

# Set to true in case you want to have filter debug information
output_debug: true

# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 1.0
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0

# list of static transformations
static_transformations: []

--- name:bumblebee_stereo_noise
# Measurement uncertainty in meters at the sensor plane projection.
# ex = 0.1462 pixel^2 ey = 0.16428 pixel^2 noise
measurement_covariance:
  rows: 2
  cols: 2
  data: [0.05, 0.00,
        0.00, 0.05]
#  data: [0.00018, 0.00,
#        0.00, 0.0002]

# Time in s between pose_samples readings
delta_pose_samples_period: 0.08
visual_features_samples_period: 0.4

--- name:bumblebee_mono_noise
# Measurement uncertainty in meters at the sensor plane projection.
measurement_covariance:
  rows: 2
  cols: 2
  data: [0.000092225, 0.00,
        0.00, 0.000098274]

# Time in s between pose_samples readings
delta_pose_samples_period: 0.08
visual_features_samples_period: 0.4

--- name:no_update
# Filter update type
update_type: :NO_UPDATE

