--- name:default

# From Frame for the transformer
localization_source_frame: 'body'

# the global name that should be used for the internal navigation frame
navigation_frame: navigation
# the global name that should be used for the internal world frame
# It is also used by the localization to get the reference frame in which
# the body position can be used.
world_frame: navigation #world

# Time in s between pose_samples readings
delta_pose_samples_period: 0.08
visual_feature_samples_period: 0.4

# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 1.0
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0

# list of static transformations
static_transformations: []

# no documentation available for this property
#metadata:
#  metadata: []
#  properties: []
#  input_ports: []
#  output_ports: []
#
