--- name:default
# Time in s between actuator_samples readings
actuator_samples_period: 0.08
# the frame name for the body frame
body_frame: body
# the global name that should be used for the internal imu_world frame
#imu_world_frame: imu

# configuration struct for the asguard odometry class
odometry_config:
  seed: 42
  constError:
    translation:
      data:
      - 0.002
      - 0.005
      - 0.001
    yaw: 0.0001
  distError:
    translation:
      data:
      - 0.1
      - 0.5
      - 0.0
    yaw: 0.0
  tiltError:
    translation:
      data:
      - 0.1
      - 0.5
      - 0.0
    yaw: 0.0
  dthetaError:
    translation:
      data:
      - 0.2
      - 0.0
      - 0.0
    yaw: 0.0
  useZeroVelocity: true

# the frame name for the odometry frame
odometry_frame: navigation

# list of static transformations
static_transformations: []
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.1
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 0.08
# If this value is set to true, the position field of the actuator samples will be used to calculate the translation
usePosition: false

# wheel base
leftWheelNames: [fl_translation, ml_translation, rl_translation]
# wheel base
rightWheelNames: [fr_translation, mr_translation, rr_translation]

--- name:exoter
# track width
trackWidth: 0.620
# wheel base
wheelBase: 0.530


