--- name:default
# the global name that should be used for the internal world frame
#world_frame: world
world_frame: navigation

# the global name that should be used for the internal navigation frame
navigation_frame: navigation

# the global name that should be used for the internal body frame
body_frame: body

# Time in s between delta_pose_samples readings
delta_pose_samples_period: 0.08

# Minimum (vector[0]) and Maximum (vector[1]) expected GP residual.
gaussian_process_residual_boundary:
    data:
    - 0.00001 #Minimum 1mm/s
      #- 0.0075 #Maximum as 12.5% * 6cm/s. This is equivalent to 1% of distance traverse
    - 0.0150 #Maximum as 25% * 6cm/s. This is equivalent to 2% of distance traverse
      #- 0.0375 #Maximum as 62.5% * 6cm/s. This is equivalent to 5% of distance traverse
      #- 0.075 #Maximum as 125% * 6cm/s. This is equivalent to 10% of distance traverse

# Minimum (vector[0]) and Maximum (vector[1]) for inliers matches ratio of the adaptive keyframe criteria (normally 0.30 - 0.75).
inliers_matches_ratio_boundary:
    data:
    - 0.30
    - 0.75

# Minimum (vector[0]) and Maximum (vector[1]) for map/vo matches ratio of the adaptive keyframe criteria (normally 0.1 - 0.35).
map_matches_ratio_boundary:
    data:
    - 0.10
    - 0.35

# Unit error (0 - 1) for odometry velocity estimation [m/s].
error_residual_threshold: 0.25 #25.0% is equivalent to 2.0% (0.02 / 0.08) of distance traverse at 12.5 Hz (frequency of the odometry)

# resize algorithm which is used to scale the frame before it is written to the output port. 
resize_algorithm: :INTER_LINEAR

# Frame of the slam localization (normally sensor frame or body frame)The slam localization target frame is taken from the world frame of the transformer.
pose_samples_out_source_frame: 'body'

# Last key frame pose of the slam (normally "last_kf")
keyframe_samples_out_source_frame: 'last_kf'

# Path to the file with the Bag-of-Words vocabulary for for the ORB descriptor.
orb_vocabulary: "<%= ENV['AUTOPROJ_CURRENT_ROOT'] %>/install/share/orb_slam2/ORBvoc.txt"

# Configuration parameters for the conditional removal filter applied to map
map_conditional_removal_config:
    filter_on: false

# minimum time, in s, between two sequential samples arrive on point_cloud_samples
point_cloud_samples_period: 0.4 #it needs to be changed in the running script

# Set to true if output debug information is desirable.
output_debug: true

--- name:bumblebee
# the global name that should be used for the internal sensor frame
sensor_frame: left_camera

# Path to the file with the camera calibration and ORB features parameters.
orb_calibration: "<%= ENV['AUTOPROJ_CURRENT_ROOT'] %>/bundles/exoter/data/orb_slam2/bumblebee_calibration.txt"

# Minimum period to adaptively compute the image processing step in seconds. It cannot be smaller than the input port period.
minimum_frame_period: 2.8 # better multiple of left_frame_period (n * 0.4)

# minimum time, in s, between two sequential samples arrive on left_frame
left_frame_period: 0.4

# minimum time, in s, between two sequential samples arrive on right_frame
right_frame_period: 0.4

# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0

# maximum latency, in seconds, of the stream aligner. The aligner will start
# dropping samples if the difference between the last output and last input is
# greater than this
transformer_max_latency: 1.0

# Calibration parameter for the frame_helper
calib_parameters:
  camLeft:
    fx: 837.98636
    fy: 838.56569
    cx: 509.74846
    cy: 376.99711
    d0: -0.35914
    d1: 0.16317
    d2: 0.00039
    d3: 0.00041
    ex: 0.06887
    ey: 0.08192
    width: 1024
    height: 768
  camRight:
    fx: 837.40801
    fy: 838.06473
    cx: 536.53701
    cy: 377.66591
    d0: -0.35499
    d1: 0.15218
    d2: 0.00019
    d3: -0.00016
    ex: 0.07723
    ey: 0.08236
    width: 1024
    height: 768

#Distance between left and right camera
  extrinsic:
    tx: 0.12042814 #baseline in x (meters)
    ty: 0.00063857 #baseline in y (meters)
    tz: 0.0003051 #baseline in z (meters)
    rx: 0.00125 #rotation along x (rad)
    ry: -0.00333 #rotation along y (rad)
    rz: 0.00542 #rotation along z (rad)

--- name:arl_map
# Point cloud resolution of the combined point clouds.'
map_point_cloud_resolution:
    data:
    - 0.01
    - 0.01
    - 0.01

# resulting ply file
output_ply: 'arl_map_point_cloud.ply'

# Configuration parameters for the conditional removal filter applied to map
map_conditional_removal_config:
    filter_on: true
    keep_organized: false
    gt_boundary:
        data:
        - 0.00
        - 0.00
        - -0.30
    lt_boundary:
        data:
        - 10.0
        - 10.0
        - 2.00


--- name:decos_map
# Point cloud resolution of the combined point clouds.'
map_point_cloud_resolution:
    data:
    - 0.02
    - 0.02
    - 0.02

# resulting ply file
output_ply: 'decos_map_point_cloud.ply'

# Configuration parameters for the conditional removal filter applied to map
map_conditional_removal_config:
    filter_on: true
    keep_organized: false
    gt_boundary:
        data:
        - -.inf
        - -.inf
        - -.inf
    lt_boundary:
        data:
        - .inf
        - .inf
        - .inf
