--- name:default

# From Frame for the transformer
sam_localization_source_frame: 'sam'

# From Frame for the transformer
odometry_localization_source_frame: 'body'

# Error per distance traveled (0 - 1).
error_per_distance_traveled: 0.02

# Minimum distance (in meters) to set a new node for the optimization.
distance_segment: 0.2

# the global name that should be used for the internal body frame
body_frame: body

# the global name that should be used for the internal sensor frame
sensor_frame: body

# the global name that should be used for the internal world frame
world_frame: navigation

# the global name that should be used for the internal navigation frame
navigation_frame: navigation

# Set to true in case you want to have filter debug information
output_debug: true

# resulting ply file
output_ply: 'point_cloud_map.ply'

# Time in s between delta_pose_samples readings
delta_pose_samples_period: 0.08

# Time in s between point_cloud_samples readings
point_cloud_samples_period: 0.5

# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 1.0
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0

outlier_config:
  type: NONE

# Voxel size in meters of the downsample point cloud
downsample_size: 0.01

--- name:tof_camera
# PCL Point clouds needs to be organized. It will take this property to organize them.
sensor_point_cloud_height: 144
# PCL Point clouds needs to be organized. It will take this property to organize them.
sensor_point_cloud_width: 176

--- name:bilateral
# Configuration parameters for the bilateral filter.
bfilter_config:
  filterOn: true
  spatial_width: 2.0 #size of the window bilateral filter
  range_sigma: 0.1 #the standard deviation of the Gaussian for the intensity difference

--- name:radius
# Configuration parameters for Radius Outlier Removal filter.
outlier_config:
  type: RADIUS
  parameter_one: 0.2 #Get the radius of the sphere that will determine which points are neighbors.
  parameter_two: 300 #number of neighbors that need to be present in order to be classified as an inlier

--- name:statistical
# Configuration parameters for Radius Outlier Removal filter.
outlier_config:
  type: STATISTICAL
  parameter_one: 30 #the number of nearest neighbors to use for mean distance estimation (nr_k)
  parameter_two: 1.0 #the standard deviation multiplier for the distance threshold calculation.(stddev_null)

--- name:sift_keypoints_10_percent
# Configuration parameters for SIFT Keypoints.
sift_config:
    min_scale: 0.08
    nr_octaves: 10
    nr_octaves_per_scale: 10
    min_contrast: 5.0

--- name:sift_keypoints_5_percent
# Configuration parameters for SIFT Keypoints.
sift_config:
    min_scale: 0.08
    nr_octaves: 10
    nr_octaves_per_scale: 10
    min_contrast: 2.0

--- name:fpfh_feature
# Configuration parameters for Feature descriptor.
feature_config:
    normal_radius: 0.1
    feature_radius: 1.0



