--- name:default
# the global name that should be used for the internal body frame
body_frame: body

# the global name that should be used for the internal navigation frame
navigation_frame: navigation

# the global name that should be used for the internal world frame
world_frame: navigation

# Time in s between delta_pose_samples readings
delta_pose_samples_period: 0.08

# Frame of the Visual Stereo localization (normally "vsd_slam" frame) The Visual Stereo localization target frame is taken from the world frame of the transformer.
slam_localization_source_frame: 'vsd_slam'

--- name:bumblebee
# the global name that should be used for the internal sensor frame
sensor_frame: left_camera

# Frame of the Odometry localization (normally sensor_frame value of the transformer) The odometry localization target frame is taken from the last SAM localization source frame.
odometry_localization_source_frame: 'left_camera'

# Time in s between visual_features_samples readings
visual_features_samples_period: 0.4

# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.8

# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0

# Intrinsic and extrinsic camera calibration parametersfor a full parameter list have a look at frame_helper
calib_parameters:
  camLeft:
    fx: 837.98636
    fy: 838.56569
    cx: 509.74846
    cy: 376.99711
    d0: -0.35914
    d1: 0.16317
    d2: 0.00039
    d3: 0.00041
    ex: 0.06887
    ey: 0.08192
    width: 1024
    height: 768
  camRight:
    fx: 837.40801
    fy: 838.06473
    cx: 536.53701
    cy: 377.66591
    d0: -0.35499
    d1: 0.15218
    d2: 0.00019
    d3: -0.00016
    ex: 0.07723
    ey: 0.08236
    width: 1024
    height: 768

#Distance between left and right camera
  extrinsic:
    tx: 0.12042814 #baseline in x (meters)
    ty: 0.00063857 #baseline in y (meters)
    tz: 0.0003051 #baseline in z (meters)
    rx: 0.00125 #rotation along x (rad)
    ry: -0.00333 #rotation along y (rad)
    rz: 0.00542 #rotation along z (rad)

